### ISSUE TITLE
Cache Vagrant ssh info

### ISSUE THREAD

**Issue by granders** [confluentinc/ducktape#114]
Fetching vagrant ssh info every test run is slow: 10 - 30 seconds for me locally, and one user has reported up to a minute!

The cluster information shouldn't change very often, so we could cache this information in a file.

So what to do if the cache is out of date?
One solution is to update the Vagrant cluster implementation:
- cache ssh info (or rather the json containing this info) to a file
- if the file is present, use it
- if the file is present, warn the user that we're using cached ssh info, and if they have updated the cluster, they should remove the file to allow Vagrant cluster to refresh the ssh info

**Comment by lindong28** [comment]
Instead of having user explicit removing the file from disk, it is probably more intuitive to provide command line option for user. How about the following scheme:

1) by default Ducktape will always fetch Vagrant ssh info and cached the retrieved info in a file
2) if specified --use-cached-info is specified AND cached info is not available, then same as 1)
3) if specified --use-cached-info is specified AND cached info is available, then use cached info

**Comment by granders** [comment]
Yeah, a flag would make manual file deletion unnecessary, which is better. One question I have about such a flag is whether it's generic enough to apply to potentially different cluster types. Maybe it is?

I'd opt for the default behavior to use the cache if it's present, since this will be the most frequent use-case. In other words:

Default: use cache if present; else, lookup `ssh-config` and repopulate cache
`--refresh-cluster` flag: lookup `ssh-config` and repopulate cache

**Comment by lindong28** [comment]
@granders Currently I assume this is only useful for VagrantCluster. I don't think we need to apply this flag to other cluster types like localhost unless there is reason to do so. What do you think?

While this is indeed the most frequent use-case, I am sill in favor of not using cache by default, because correctness is more important than performance. If default behavior is to use cache, and user has re-initialized the virtual machine, then their future ducktape test will fail by default. It is usually easy to say "this flag will improve your performance" than saying "your job may fail without this flag". Just my 2c.
