### ISSUE TITLE
Kafka broker startup async

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ducktape#185]
Atm, if you set up a Kafka cluster and call `kafka.start()`, this call is aync. This can lead to a race condition if an application wants to create a topic but not all brokers are available yet.

For example:
```
org.apache.kafka.streams.errors.StreamsException: Could not create topic SmokeTest-cntByCnt-repartition.
	at 
...
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 2.
	at
...
Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 2.
```

**Comment by ewencp** [comment]
@mjsax Presumably this should be filed against Kafka? `start` isn't fundamentally async in ducktape, it's up to the Service implementation to block until it is actually running. Seems like `KafkaService` may not be doing this? See https://github.com/apache/kafka/blob/trunk/tests/kafkatest/services/kafka/kafka.py#L161-L175 and https://github.com/apache/kafka/blob/trunk/tests/kafkatest/services/kafka/kafka.py#L217-L242. In particular https://github.com/apache/kafka/blob/trunk/tests/kafkatest/services/kafka/kafka.py#L233 is what we currently block on, but perhaps we need to wait on something different. *If* your test uses jmx, it will also wait on the JMX port to be accessible and the ability to get JMX data https://github.com/apache/kafka/blob/trunk/tests/kafkatest/services/monitor/jmx.py#L84-L87.

This type of issue has been an ongoing theme recently -- actually getting the condition you need to wait on correct can be difficult. I think a lot of the reason is as much because getting JMX metrics is just super painful, but probably a lot of the time metrics give the right condition. That's part of why I added https://github.com/apache/kafka/pull/4072 in Kafka -- I wanted a way to grab metrics that wasn't as painful as jmxtool.

**Comment by mjsax** [comment]
I see. Thanks for pointing out. I opened https://github.com/apache/kafka/pull/4363
