### ISSUE TITLE
Release ducktape with the python3 fixes

### ISSUE THREAD

**Issue by nizhikov** [confluentinc/ducktape#245]
Hello!

I'm working on [KAFKA-10402](https://issues.apache.org/jira/browse/KAFKA-10402).
The goal of the ticket is to upgrade Kafka system test to python3.

For now, my [PR](https://github.com/apache/kafka/pull/9196/files#diff-9235a7bdb1ca9268681c0e56f3f3609bR39) base on the master version of the ducktape.

It seems, three following commits required to be able to switch to python3
* bfe53712f83b025832d29a43cde3de3d7803106f
* 23bd5ab53802e3a1e1da1ddf3630934f33b02305
* ecaf7173c6909d36f7ee4a2f6656b128212f8865

Can you, please, release ducktape with these commits included or provide me the guide on how to do it by myself?

**Comment by dotnwat** [comment]
I think there is at least one more py3 issue with pysistence and globals (the pickling protocol changed in py3 and breaks pysistence). I think @ivandasch may submit a patch for this very soon.

**Comment by ivandasch** [comment]
Yes, I am going to submit patch ASAP. The problem is that `pysistence` seems to be abandoned (last release at 2011) and doesn't compatible to python 3 pickle. I've found the good candidate to replace it -- [pyrsistent](https://github.com/tobgu/pyrsistent/). It is compatible both with python 2 and 3, datastructures can be flawlessly pickled-unpickled.

**Comment by nizhikov** [comment]
Hello, @ewencp. Can you, please, help me with the release of ducktape with the python3 fixes?

**Comment by ewencp** [comment]
We should get through review of the kafka PR using master, then do a release. Kafka pretty thoroughly uses ducktape features so we use it as a kind of final regression test. Unless we do a major version bump, we'd also want to make sure tests continue to work with py2. That PR probably needs some test jobs run against it to validate -- there are jenkins jobs that can be triggered against a kafka fork/branch for testing/validation. Once that's done, the final version bump change is minor.

**Comment by nizhikov** [comment]
@ewencp 

> make sure tests continue to work with py2

Do you mean "Ducktape tests should continue to work with py2?"
Or "Kafka system tests should work with py2?"

> That PR probably needs some test jobs run against it to validate

Yes, sure.
My PR to the Kafka needs to be validated on some stable testing environment.
Don't have such so I asked on the Kafka dev-list for it.

From my side, I validated PR on the Docker and run all tests.
You can find tests results in the [ticket comment](https://issues.apache.org/jira/browse/KAFKA-10402?focusedCommentId=17183036&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17183036)

**Comment by ewencp** [comment]
> @ewencp
> 
> > make sure tests continue to work with py2
> 
> Do you mean "Ducktape tests should continue to work with py2?"
> Or "Kafka system tests should work with py2?"

Ducktape is covered by testing in this repo. I meant kafka system tests. We need a migration period for CI, developers, etc.

> > That PR probably needs some test jobs run against it to validate
> 
> Yes, sure.
> My PR to the Kafka needs to be validated on some stable testing environment.
> Don't have such so I asked on the Kafka dev-list for it.
> 
> From my side, I validated PR on the Docker and run all tests.
> You can find tests results in the [ticket comment](https://issues.apache.org/jira/browse/KAFKA-10402?focusedCommentId=17183036&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17183036)

Yeah, kafka nightlies run on a real cluster on EC2, so there are multiple modes that need to be validated. A committer who is actively working on these should be able to help you trigger test jobs. The infrastructure is there but because of the cost of running these jobs, they aren't run automatically on every PR and a restricted set of users have access to trigger a job.

**Comment by nizhikov** [comment]
> We need a migration period for CI, developers, etc.

Can we just use different versions of ducktape for it?

**Comment by nizhikov** [comment]
Hello, @ewencp 

Any news on release?
Can I help with it, somehow?

**Comment by nizhikov** [comment]
Hello, @ewencp 

PR to upgrade Kafka system tests to python3 is ready to be merged - https://github.com/apache/kafka/pull/9196
All we need is ducktape release with python3 fixes.

Can you help with it?
Can I perform release by myself?

**Comment by andrewegel** [comment]
@nizhikov Please sync up with @stan-confluent regarding a 0.8.x release. Internally at confluent we're seeing an increased number of SSHExceptions that get raised on kafka-system-test runs after updating paramiko from 2.3 to 2.6 (we rolled back that change in the 0.7.x branch), so before we do a 0.8.x release from master, we need to resolve those issues so we don't "re-break" kafka-system-tests.

**Comment by nizhikov** [comment]
Hello @andrewegel @stan-confluent 

Can you, please, give me an example of `SSHException` you are facing?

**Comment by nizhikov** [comment]
@andrewegel , @stan-confluent 

Actually, we use ducktape(master branch) internally in Apache Ignite https://github.com/apache/ignite/blob/ignite-ducktape/modules/ducktests/tests/docker/requirements.txt

We don't face the issue you describe nor on docker nor on private cloud deployment.

Can you, please, provide more information?

**Comment by stan-confluent** [comment]
@nizhikov Yeah, we were facing random flakiness in our tests roughly around when we bumped paramiko to ~=2.6.0 - the same tests would occasionally raise `Unable to open channel` or `Connection timed out`. We didn't see them with an older version of paramiko, and we did some limited comparative runs with different paramiko versions to confirm, though we haven't finished. Since you don't run into these issues might indicate that this is something specific to our environment.

However, even if paramiko is the reason for that, we would still want to release 0.8.0 version of ducktape - we cannot stay on python 2 and paramiko 2.3.2 forever, so I'd rather we moved on to both python 3 and an even newer paramiko version and if `SSHException`s keep happening, we do our investigation on newer versions. 
So yeah, tl;dr we'll release 0.8.0 in the coming days -  please see the discussion on this PR: https://github.com/confluentinc/ducktape/pull/237

**Comment by nizhikov** [comment]
Hello, @stan-confluent 

Any news on ducktape 0.8 release? How can I help you with it?

**Comment by stan-confluent** [comment]
I believe this can be closed now
