### ISSUE TITLE
Can ducktape controll multiple VMs?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [confluentinc/ducktape#321]
This isn't a bug or feature. But I couldn't find another channel (mailinglist, etc) to ask.

I am experienced with unittests but not integration tests. I need a system that can handle multiple virtual machines which are part of my test cases. My tests (or use cases) involving multiple machines and network protocols.

Can ducktape take are of something like that?

Looking into the docu I am not sure. It seems to me that it is "just" a wrapper for testing tools look unittest and pytest.

**Comment by imcdo** [comment]
ducktape is designed to handle tests that use multiple machines, however it doesn't handle creation or destruction of such devices.  It has vagrant integration, but otherwise you pretty much have to set up a cluster.json file describing nodes, and how to ssh into them, then hand it to ducktape to execute tests on those machines.
